# 配置文件版本号，用于在插件更新时自动替换老版本的配置文件
configVersion: "1.1"

# 调试模式开关，当设置为 true 时，插件会在控制台输出更多的调试信息
debug: false

# 视角向上时，按下换手键(F)执行的命令配置
lookUpSwapCommand:
  command: "exampleLookUpCommand"  # 自定义命令名称或内容
  asConsole: false                 # 是否以控制台身份执行该命令

# 视角向下时，按下换手键(F)执行的命令配置
lookDownSwapCommand:
  command: "exampleLookDownCommand"
  asConsole: false

# 视角向上时，按下丢弃键(Q)执行的命令配置
lookUpDropCommand:
  command: "exampleLookUpDropCommand"
  asConsole: false

# 视角向下时，按下丢弃键(Q)执行的命令配置
lookDownDropCommand:
  command: "exampleLookDownDropCommand"
  asConsole: false

# 潜行状态下按下换手键(F)执行的命令配置
sneakSwapCommand:
  command: "exampleSneakSwapCommand"
  asConsole: false

# 潜行状态下按下丢弃键(Q)执行的命令配置
sneakDropCommand:
  command: "exampleSneakDropCommand"
  asConsole: false

creeper:
  protectTerrain: true   # 如果为 false，Creeper 爆炸会破坏地形
  explodeAsFireworks: false # 如果为 true，Creeper 爆炸会产生日程序制的烟花

messages:
  reloadSuccess: "Meowtools配置已重新加载"
  reloadNoPermission: "你没有权限执行此命令"